name: Unittest and docker builds

on:
  push:
  release:
    types: [published]

jobs:
  unittest:
    runs-on: ubuntu-latest
    env:
      NUMBA_DISABLE_JIT: 1
    steps:
      - uses: actions/checkout@v2
      # Setup miniconda nd build env
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          activate-environment: xcube
#          environment-file: environment.yml
          environment-file: conda-linux-64.lock
      # Setup xcube
      - name: setup-xcube
        shell: bash -l {0}
        run: |
          conda info
          conda list
          pip install rfc3339-validator
          python setup.py develop
      # Run unittests
      - name: unittest-xcube
        shell: bash -l {0}
        run: |
          pip install pytest pytest-cov
          mamba install -c conda-forge  flask-testing moto requests-mock

          pytest --cov=./ --cov-report=xml
      - uses: codecov/codecov-action@v1
        with:
          verbose: true # optional (default = false)
  build-docker-image:
    runs-on: ubuntu-latest
    # Only run if unittests succeed
    needs: unittest
    # Build the docker image and push to quay.io
    name: build-docker-image
    env:
      APP_NAME: xcube
      ORG_NAME: bcdev
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      # Strip the release tag from refs
      - name: get-release-tag
        id: release
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      # Print some info
      - name: info
        id: info
        run: |
          echo "TAG: ${{ steps.release.outputs.tag }}"
          echo "EVENT: ${{ github.event_name }}"
      # Build and push docker image 'latest' to quay.io when the event is a 'push' and branch 'master'
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: build-push-docker-image-latest
        if: ${{ github.event_name == 'push' && steps.release.outputs.tag == 'master'  }}
        with:
          image: ${{ env.ORG_NAME }}/${{ env.APP_NAME }}
          tags: master, latest
          registry: quay.io
          username: ${{ secrets.QUAY_DOCKER_REPO_USERNAME }}
          password: ${{ secrets.QUAY_DOCKER_REPO_PASSWORD }}
      # Build and push docker release to quay.io when the event is a 'release'
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: build-push-docker-image-release
        if: ${{ github.event_name == 'release' }}
        with:
          image: ${{ env.ORG_NAME }}/${{ env.APP_NAME }}
          tags: ${{ steps.release.outputs.tag }}
          registry: quay.io
          username: ${{ secrets.QUAY_DOCKER_REPO_USERNAME }}
          password: ${{ secrets.QUAY_DOCKER_REPO_PASSWORD }}
  update-version:
    env:
      PUSH: 0
      APP_NAME: xcube
    runs-on: ubuntu-latest
    needs: build-docker-image
    name: update-tag
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: bc-org/k8s-configs
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: k8s
      - name: get-release-tag
        id: release
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: deployment-phase
        id: deployment-phase
        uses: bc-org/gha-determine-phase@v0.1
        with:
          event_name: ${{ github.event_name }}
          tag: ${{ steps.release.outputs.tag }}
      - name: get-hash
        id: get-hash
        run: |
          HASH=$(skopeo inspect docker://quay.io/bcdev/${{ env.APP_NAME }}:${{ steps.release.outputs.tag }} | jq '.Digest')
          if [[ "$HASH" == *"sha256"* ]]; then
            echo ::set-output name=hash::$HASH
          else
            echo "No hash present. Using none as hash. This will use the version tag instead for deployment."
            echo ::set-output name=hash::none
          fi
      - name: info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Deployment Stage: ${{ steps.deployment-phase.outputs.phase }}"

          echo "Release Tag: ${{ steps.release.outputs.tag }}"
          echo "Deployment Release Tag: ${{ steps.deployment-phase.outputs.tag }}"
          echo "Deployment Digest: ${{ steps.get-hash.outputs.hash }}"
      - name: set-version-tag-xcube-gen
        uses: bc-org/update-application-version-tags@main
        with:
          app: ${{ env.APP_NAME }}
          phase: ${{ steps.deployment-phase.outputs.phase }}
          delimiter: ' '
          tag: ${{ steps.deployment-phase.outputs.tag }}
          hash: ${{ steps.get-hash.outputs.hash }}
          working-directory: "./k8s/xcube-gen/helm"
      - name: cat-result
        working-directory: "./k8s/xcube-gen/helm"
        run: |
          head values-dev.yaml
          head values-stage.yaml
          head values-prod.yaml
      - name: Pushes to another repository
        # Don't run if run locally and should be ignored
        if: ${{ steps.deployment-phase.outputs.phase != 'ignore' && !env.ACT }}
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'k8s'
          destination-github-username: 'bc-org'
          destination-repository-name: 'k8s-configs'
          user-email: bcdev@brockmann-consult.de
          target-branch: main
          commit-message: ${{ github.event.release }}. Set version to ${{ steps.release.outputs.tag }}
